export const departments = [
  { key: "0", name: "Administration", path: "/administration" },
  { key: "1", name: "Chapel Shepherd", path: "/chapel shepherd" },
  { key: "2", name: "Facilitators", path: "/facilitators" },
  { key: "3", name: "Housekeeping", path: "/housekeeping" },
  { key: "4", name: "Intercessory", path: "/intercessory" },
  { key: "5", name: "MC", path: "/mc" },
  { key: "6", name: "Media", path: "/media" },
  { key: "7", name: "Medical", path: "/medical" },
  { key: "8", name: "Men’s Ministry", path: "/men’s ministry" },
  { key: "9", name: "Music", path: "/music" },
  { key: "10", name: "Parking", path: "/parking" },
  { key: "11", name: "Protocol", path: "/protocol" },
  { key: "12", name: "Single's Ministry", path: "/single's ministry" },
  { key: "13", name: "Women’s Ministry", path: "/women’s ministry" },
  { key: "14", name: "Welfare", path: "/welfare" },
];
